import { describe, expect, it } from 'vitest';

import { parseManifest, renderMemesModule } from '../scripts/sync-memes.mjs';

describe('parseManifest', () => {
	it('accepts a well-formed manifest', () => {
		const out = parseManifest([{ id: 'a', file: 'a.jpg', alt: 'an a' }]);
		expect(out).toEqual([{ id: 'a', file: 'a.jpg', alt: 'an a' }]);
	});

	it('rejects a non-array', () => {
		expect(() => parseManifest({ id: 'a' })).toThrow(/must be a JSON array/);
	});

	it('rejects an entry missing a field', () => {
		expect(() => parseManifest([{ id: 'a', file: 'a.jpg' }])).toThrow(/alt must be a non-empty string/);
	});

	it('rejects an empty-string field', () => {
		expect(() => parseManifest([{ id: 'a', file: 'a.jpg', alt: '  ' }])).toThrow(/alt must be a non-empty string/);
	});

	it('rejects a path in file (must be a bare filename)', () => {
		expect(() => parseManifest([{ id: 'a', file: 'sub/a.jpg', alt: 'x' }])).toThrow(/bare filename/);
	});

	it('rejects duplicate ids', () => {
		expect(() =>
			parseManifest([
				{ id: 'a', file: 'a.jpg', alt: 'x' },
				{ id: 'a', file: 'b.jpg', alt: 'y' },
			]),
		).toThrow(/duplicate manifest id "a"/);
	});
});

describe('renderMemesModule', () => {
	it('derives src from file and emits a do-not-edit header', () => {
		const src = renderMemesModule([{ id: 'hac', file: 'hac.jpg', alt: 'meme man' }]);
		expect(src).toContain('@generated by scripts/sync-memes.mjs');
		expect(src).toContain("src: \"/images/memes/hac.jpg\"");
		expect(src).toContain("id: \"hac\"");
	});

	it('escapes quotes and apostrophes in alt text into valid TS', () => {
		const alt = 'guy: "I\'ve never met this man"';
		const src = renderMemesModule([{ id: 'x', file: 'x.jpg', alt }]);
		// JSON.stringify escaping keeps the double-quote string literal valid.
		expect(src).toContain(`alt: ${JSON.stringify(alt)},`);
	});

	it('is deterministic for the same input', () => {
		const entries = [{ id: 'x', file: 'x.jpg', alt: 'x' }];
		expect(renderMemesModule(entries)).toBe(renderMemesModule(entries));
	});
});
