// Build-time sync for the memes gallery (#250). Reads a manifest of
// { id, file, alt } from the tech-memes source of truth, copies the image
// files into public/images/memes/, and regenerates src/data/memes.ts so the
// gallery is no longer hand-maintained in two places.
//
// The pure functions (parseManifest, renderMemesModule) are exported and
// unit-tested; main() is the CLI wiring. Pre-seed (no manifest present) main()
// no-ops with a clear message so the build never breaks before tech-memes
// carries a manifest — see docs/runbooks/memes-sync.md for activation.
//
// Usage: node scripts/sync-memes.mjs <manifest.json> <images-src-dir>

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const IMAGES_DEST = 'public/images/memes';
const MODULE_DEST = 'src/data/memes.ts';

/**
 * Validate + normalize a parsed manifest into Meme entries.
 * Throws on a malformed manifest rather than emitting a broken module.
 *
 * @param {unknown} data Parsed JSON manifest.
 * @returns {{ id: string, file: string, alt: string }[]}
 */
export function parseManifest(data) {
	if (!Array.isArray(data)) {
		throw new Error('manifest must be a JSON array of { id, file, alt } objects');
	}
	const seen = new Set();
	return data.map((raw, i) => {
		if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) {
			throw new Error(`manifest[${i}] must be an object`);
		}
		const { id, file, alt } = raw;
		for (const [key, value] of [['id', id], ['file', file], ['alt', alt]]) {
			if (typeof value !== 'string' || value.trim() === '') {
				throw new Error(`manifest[${i}].${key} must be a non-empty string`);
			}
		}
		if (basename(file) !== file) {
			throw new Error(`manifest[${i}].file must be a bare filename, got "${file}"`);
		}
		if (seen.has(id)) {
			throw new Error(`duplicate manifest id "${id}" — ids must be stable and unique`);
		}
		seen.add(id);
		return { id, file, alt };
	});
}

/**
 * Render the generated src/data/memes.ts module source for the given entries.
 * String fields go through JSON.stringify so quotes/apostrophes in alt text
 * are escaped into valid TypeScript.
 *
 * @param {{ id: string, file: string, alt: string }[]} entries
 * @returns {string}
 */
export function renderMemesModule(entries) {
	const head = [
		'// @generated by scripts/sync-memes.mjs — DO NOT EDIT.',
		'// Source of truth: tech-memes/memes.json. Regenerate with',
		'// scripts/sync-memes.mjs — see docs/runbooks/memes-sync.md.',
		'',
		'export interface Meme {',
		'\treadonly id: string;',
		'\treadonly src: string;',
		'\treadonly alt: string;',
		'}',
		'',
		'export const memes: readonly Meme[] = [',
	];
	const body = entries.map((e) => {
		const lines = [
			'\t{',
			`\t\tid: ${JSON.stringify(e.id)},`,
			`\t\tsrc: ${JSON.stringify(`/images/memes/${e.file}`)},`,
			`\t\talt: ${JSON.stringify(e.alt)},`,
			'\t},',
		];
		return lines.join('\n');
	});
	return [...head, ...body, '];', ''].join('\n');
}

function main(argv) {
	const [manifestPath, imagesSrcDir] = argv;
	if (!manifestPath || !imagesSrcDir) {
		// eslint-disable-next-line no-console
		console.log('sync-memes: no manifest/images path supplied — nothing to sync (pre-seed no-op).');
		return;
	}
	const entries = parseManifest(JSON.parse(readFileSync(manifestPath, 'utf8')));
	mkdirSync(IMAGES_DEST, { recursive: true });
	for (const e of entries) {
		try {
			copyFileSync(join(imagesSrcDir, e.file), join(IMAGES_DEST, e.file));
		} catch (cause) {
			throw new Error(
				`manifest entry "${e.id}" references image "${e.file}" missing from ${imagesSrcDir}`,
				{ cause },
			);
		}
	}
	writeFileSync(MODULE_DEST, renderMemesModule(entries));
	// eslint-disable-next-line no-console
	console.log(`sync-memes: wrote ${entries.length} memes to ${MODULE_DEST} and copied images to ${IMAGES_DEST}/`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
	main(process.argv.slice(2));
}
